### ISSUE TITLE
changes for newest HyLang version

### ISSUE THREAD

**Issue by mark-watson** [philiparvidsson/LSTM-Text-Generation#3]
for the latest version of HyLang, I had to change lines 23 and 24 to:

          self.char-to-index    (dict (lfor i (enumerate chars) (, (last i) (first i))))
          self.index-to-char    (dict (lfor i (enumerate chars) i)))

It is not worth a pull request for two lines, but you might want to make these changes.

**Comment by philiparvidsson** [comment]
thank you for this! I'll make the change
